
name: Build and Test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: rustup
        uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
      - name: Cache build data
        uses: actions/cache@v2
        with:
          path: |
            target
            ~/.cargo/
          key: ${{ runner.os }}-cargo-${{ hashFiles('Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Fast Fail Check
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --verbose

      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --verbose --all-features

      - name: Run tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --verbose --all-features
